import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import React from "react";
import Login from "./login/page";
import Register from "./registrar/page";
import Footer from "@/components/Footer";
import { AuthProvider } from "./context";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Challenge FIAP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthPage =
  React.isValidElement(children) &&
  (children.type === Login || children.type === Register);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          {!isAuthPage && <Header />}
          {children}
          {!isAuthPage && <Footer/>}
        </AuthProvider>
      </body>
    </html>
  );
}
